name: dddrop_flutter_dev_utilities
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.2
  dartz: ^0.10.1
  flutter_hooks: ^0.18.4
  go_router: ^3.1.1
  hooks_riverpod: ^2.0.0-dev.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  filterable_logger: ^0.0.6

flutter:
