name: dddrop_flutter_dev_utilities
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  dartz: ^0.10.1
  flutter_hooks: ^0.18.6
  go_router: ^7.0.0
  hooks_riverpod: ^2.3.6
  filterable_logger: ^0.0.7
  flutter_svg: ^2.0.5
  google_maps_flutter: ^2.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
